feat: added user profile components
lautarolombardi/TraineeTeam-Front pull request #14
Opened 2023-03-20 21:16 UTC by rafaeldoleo14

Se agrego el componente que ira en la page UserProfilePage (cuando sea creada)

2023-03-22 13:49 UTC, lautarolombardi requested changes
Cambiar los componentes internos a export default

2023-03-22 17:18 UTC, malks14 requested changes
ver lo comentarios

2023-03-22 17:18 UTC, malks14 commented on TraineeTeam/src/components/UserProfile/ProfileAccount.css
> +a{
en este caso, no uses selectores generales. si queres usarlos asi, usa modulos

2023-03-22 17:18 UTC, malks14 commented on TraineeTeam/src/components/UserProfile/ProfileAccount.tsx
> +    <>
no pongas los fragmentos, ya el div te cubre todo

2023-03-22 17:18 UTC, malks14 commented on TraineeTeam/src/components/UserProfile/ProfileInfo.tsx
> +    <>
no usar fragmentos, se devuelve un solo elemento (div)

2023-03-22 17:18 UTC, malks14 commented on TraineeTeam/src/components/UserProfile/ProfilePortafolio.tsx
> +    <>
fragment

2023-03-22 17:18 UTC, malks14 commented on TraineeTeam/src/components/UserProfile/ProfilePublic.tsx
> +    <>
fragment

2023-03-22 17:18 UTC, malks14 commented on TraineeTeam/src/components/UserProfile/UserProfile.tsx
> +    <>
fragment

2023-03-22 17:18 UTC, malks14 commented on TraineeTeam/src/components/UserProfile/ProfilePublic.tsx
> +export const ProfilePublic = () => {
preparar componente para que reciba props y cambiar a export default

2023-03-22 17:18 UTC, malks14 commented on TraineeTeam/src/components/UserProfile/ProfileAccount.tsx
> +export const ProfileAccount = () => {
preparar componente para que reciba props y cambiar a export default

2023-03-23 17:13 UTC, malks14 approved these changes

2023-03-23 17:17 UTC, lautarolombardi approved these changes

2023-03-23 17:17 UTC, merged